export const siteConfig = {
  name: "Nazmul H. Sourab | Software Engineer",
  authorName: "Nazmul H. Sourab",
  designation: "Software Engineer",
  companyName: "TechnoNext Software Ltd",
  companyURL: "https://technonext.com",
  username: "mdnhs",
  description:
    "🚀 Software Engineer | Experienced in React.js, Next.js, TypeScript & Tailwind CSS | Passionate about building performant, scalable, and modern web applications ✨",
  url: "https://www.nazmulhsourab.com",
  links: {
    twitter: "https://x.com/mdnhs_cse",
    github: "https://github.com/mdnhs",
    linkedIn: "https://linkedin.com/in/mdnhs",
    mail: "mailto:mdnhs@example.com",
  },
  ogImage: "/profile-photo.png",
  iconIco: "/profile-photo.png",
  logoIcon: "/profile-photo.png",
  keywords: [
    "Nazmul H. Sourab",
    "Nazmul Hasan Sourab",
    "Nazmul Hasan",
    "Frontend Engineer",
    "Software Engineer",
    "Frontend Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "JavaScript Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Tailwind CSS portfolio",
    "Shadcn UI portfolio",
    "Modern web developer portfolio",
    "Bangladesh Frontend Developer",
    "Dhaka Software Engineer",
    "Next.js 14 portfolio",
    "Responsive portfolio website",
    "Professional developer portfolio",
    "Frontend projects showcase",
    "Personal developer website",
  ],
};
